"""Package CPU stills, measurements and candid review in a separate static page."""
from pathlib import Path
import json,sys,shutil,html,hashlib,numpy as np
from PIL import Image,ImageDraw,ImageFont
R=Path(__file__).resolve().parent;sys.path.insert(0,str(R));from cpu_catalog import catalog
cpu=R/'cpu';out=R.parents[2]/'outputs/cybrdelic-type/elements/motion/subelements/cpu-review';out.mkdir(parents=True,exist_ok=True);(out/'images').mkdir(exist_ok=True)
reviews=json.loads((cpu/'reviews.json').read_text());cards=[];allruns=[];metadata=[]
for recipe in catalog():
 k=recipe['id'];runs=[]
 for p in (cpu/'proofs'/k).glob('*/run.json'):
  a=json.loads(p.read_text());allruns.append(a)
  if a['status']=='complete':runs.append((p,a))
 assert runs,('Missing CPU image',k)
 byframe={}
 for p,a in sorted(runs,key=lambda x:x[0].stat().st_mtime):byframe[a['frame']]=(p,a)
 preferred=byframe.get(recipe['frame'],next(iter(byframe.values())));variants=[]
 for f,(p,a) in sorted(byframe.items()):
  source=p.parent/a['images'][0];im=Image.open(source);im.load();pixels=np.asarray(im);assert im.size==(512,384);meta=json.loads(source.with_suffix('.json').read_text());assert meta['device']=='CPU' and not meta['denoisingGPU'];assert hashlib.sha256(source.read_bytes()).hexdigest()==meta['sha256']
  filename=f'{k}-{f:04}-{a["key"]}.png';shutil.copy2(source,out/'images'/filename);data={'frame':f,'src':'images/'+filename,'seconds':a['seconds'],'peakMB':a['peakResidentMB'],'device':meta['device'],'samples':meta.get('samples'),'sha256':meta['sha256'],'litPixelFraction':float((pixels.max(2)>12).mean()),'clippedPixelFraction':float((pixels.max(2)>=254).mean())};variants.append(data);metadata.append({'kind':k,**data})
 primary=next(x for x in variants if x['frame']==preferred[1]['frame']);entry={'id':k,'family':recipe['family'],'image':primary,'frames':variants,**reviews[k]};cards.append(entry)
stats={'materials':len(cards),'diagnosticImages':len(metadata),'renderAttempts':len(allruns),'successfulAttempts':sum(x['status']=='complete' for x in allruns),'combinedRenderProcessSeconds':round(sum(x['seconds'] for x in allruns),1),'largestResidentMB':max(x['peakResidentMB'] for x in allruns),'imageDimensions':[512,384],'threadsPerRender':2,'GPUUsed':False,'fullMoviesGenerated':0,'productionReady':False}
(out/'proofs.json').write_text(json.dumps({'stats':stats,'materials':cards,'imageValidation':metadata},indent=2));(cpu/'image-validation.json').write_text(json.dumps(metadata,indent=2));(cpu/'summary.json').write_text(json.dumps(stats,indent=2))
for name in ['audit.json','material-tests.json','protected.json','reviews.json']:shutil.copy2(cpu/name,out/name)
font=ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',18)
for page in range(2):
 im=Image.new('RGB',(1536,990),(12,12,14));draw=ImageDraw.Draw(im)
 for i,card in enumerate(cards[page*12:page*12+12]):
  x=(i%4)*384;y=(i//4)*330;pic=Image.open(out/card['image']['src']);pic.thumbnail((384,288));im.paste(pic,(x,y+34));draw.text((x+12,y+5),card['id'],font=font,fill=(221,230,224))
 im.save(out/f'contact-{page+1}.jpg',quality=92)
body=[]
for c in cards:
 k=c['id'];buttons=''.join(f'<button type="button" data-frame="{v["frame"]}" data-source="{html.escape(v["src"])}">{v["frame"]/30:.2f}s</button>' for v in c['frames'])
 body.append(f'<article id="{k}"><header><h2>{html.escape(k.replace("-"," "))}</h2><span>{html.escape(c["status"])}</span></header><a class="image-link" href="{c["image"]["src"]}"><img width="512" height="384" loading="lazy" src="{c["image"]["src"]}" alt="CPU diagnostic for {k}"></a><nav aria-label="Sample times">{buttons}</nav><p>{html.escape(c["finding"])}</p><details><summary>Change and remaining work</summary><p><b>Implemented:</b> {html.escape(c["implemented"])}</p><p><b>Remaining:</b> {html.escape(c["next"])}</p></details><footer>CPU · 512 × 384 · {c["image"]["seconds"]:.1f}s render process</footer></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cybrdelic · CPU material review</title><style>
*{box-sizing:border-box}body{margin:0;background:#080909;color:#dce4df;font:15px/1.55 system-ui,sans-serif}main{max-width:1550px;margin:auto;padding:45px 28px}h1{font-size:clamp(30px,4vw,54px);line-height:1.08;letter-spacing:-.04em;margin:10px 0 20px}h2{font-size:17px;font-weight:580;text-transform:capitalize;margin:0}a{color:#9bc6b3}p{max-width:850px}.eyebrow{color:#91a59a;text-transform:uppercase;letter-spacing:.18em;font-size:11px}.intro{color:#9ba9a1}.stats{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0}.stats span{padding:6px 12px;border:1px solid #28322e;border-radius:20px;font-size:12px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:34px}article{border:1px solid #26302b;background:#101411;min-width:0}article header{padding:16px 16px 10px;display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:6px}article header span{font-size:10px;text-transform:uppercase;color:#cab986;letter-spacing:.05em}img{width:100%;height:auto;display:block;background:#000}article p,details{margin:12px 16px;color:#adbab2;font-size:13px}details p{margin:10px 0}summary{cursor:pointer;color:#d4dfd8}nav{display:flex;gap:6px;padding:10px 16px 0}button{border:1px solid #36483e;background:#17221b;color:#c9d9cf;border-radius:4px;padding:4px 9px;cursor:pointer}button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid #a6ddbe;outline-offset:3px}footer{padding:12px 16px;border-top:1px solid #222e26;font-size:10px;color:#83958a}.links{display:flex;flex-wrap:wrap;gap:20px;margin:20px 0;font-size:13px}@media(min-width:1400px){.grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:850px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:540px){main{padding:28px 14px}.grid{grid-template-columns:1fr}}
</style><main><div class="eyebrow">Cybrdelic / material development / CPU</div><h1>Inspect before rendering.</h1><p class="intro">Small CPU images and material checks for all 23 effects. These are development proofs. Several mechanisms still fail the visual or physical requirements; no final movies are approved by this review.</p>'''
page+=f'<div class="stats"><span>23 materials</span><span>{len(metadata)} retained images</span><span>CPU rendering only</span><span>26 numerical checks passed</span><span>0 full movies generated</span><span>Pitch-black camera background</span></div><p class="intro">The shared motion study is used for comparison. Healing and projection use the original sigil. Both original wordmark masters remain protected; the full 01/02 film batch stays paused.</p><div class="links"><a href="contact-1.jpg">Material contact sheet</a><a href="contact-2.jpg">Field contact sheet</a><a href="report.md">Implementation report</a><a href="material-tests.json">CPU checks</a><a href="proofs.json">Image receipts</a><a href="../dynamics/">Existing gallery</a></div><section class="grid">'+''.join(body)+'</section></main>'
page+='''<script>document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{const a=b.closest('article');a.querySelector('img').src=b.dataset.source;a.querySelector('.image-link').href=b.dataset.source;a.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));</script></html>''';(out/'index.html').write_text(page,encoding='utf-8')
report=['# Cybrdelic CPU-first material pass','', 'This completes the CPU diagnostic stage, not the full physical rebuild or the 52-film sigil batch. No GPU rendering was launched. No candidate was promoted to the production gallery.','', '## Implemented','', '- CPU-only Cycles and NumPy entry points, 512 × 384 images, 24 samples for Cycles, two render threads, serial execution, 100-second and 3 GiB limits per process. New runs also enforce affinity to two logical processors.', '- Source-keyed reuse and image hashes; GPU and full-movie queues are held. Original sigil data and vector masters have protected hashes.', '- Consistent face orientation and closed metal ends; foam radius correction and exclusion of severely overlapping cells; continuous seismic sample interpolation.', '- CPU preparation of original-vector sigil repair and projection; acceleration-driven leaf lag; distinct sound/pressure witnesses; coherent spirit/energy field bundles; lightning leader and selective restrikes.', '- 26 numerical checks, including actual geometry/cache checks and isolated material-law tests. The latter do not certify integration into a complete scene solver.','', '## Evidence','',f'- {stats["materials"]} materials have successful CPU diagnostic images; {stats["diagnosticImages"]} distinct current material/frame images are retained in the page.',f'- All render attempts together used {stats["combinedRenderProcessSeconds"]:.1f} seconds of render-process wall time. This is not a measurement of total CPU core-seconds.',f'- Maximum observed resident memory: {stats["largestResidentMB"]:.1f} MiB.', '- Every retained image decodes to 512 × 384, matches its SHA-256 receipt, and reports CPU rendering with GPU denoising disabled.', '- Representative contact sheets and temporal samples were inspected directly. Numerical checks do not replace that review.','', '## Remaining work by material','']
for c in cards:report.extend([f'### {c["id"]}', '',c['finding'],'',f'Implemented: {c["implemented"]}','',f'Remaining: {c["next"]}',''])
report.extend(['## Reproduce without GPU','', 'Run from the workspace root using Python:','', '```text','python work/element-motion/material-rebuild/cpu_audit.py','python work/element-motion/material-rebuild/cpu_material_tests.py','python work/element-motion/material-rebuild/cpu_run.py --kinds metal','python work/element-motion/material-rebuild/cpu_review.py','```','', 'Additional images should answer a specific unresolved question. Do not restart the full batches merely because the diagnostic scripts run successfully.'])
(out/'report.md').write_text('\n'.join(report),encoding='utf-8');(cpu/'REPORT.md').write_text('\n'.join(report),encoding='utf-8');print(json.dumps({'output':str(out),'stats':stats}))
