#!/usr/bin/env python3
"""CYBR ELEMENTS trajectory-driven avatar combat bridge.

The existing CYBR ELEMENTS repository contains specialized production solvers
for the sigil films. Those solvers assume fixed source geometry. This module
adds a generic world-space adapter for an animated actor: it consumes weapon
and hand trajectories, evolves deterministic volumetric fields, reconstructs
moving elemental meshes, and writes assets that CYBR LIGHT can consume.

This is graphics simulation, not an engineering CFD/electromagnetics model.
No frame is generated by an image model and no screen-space effect is used.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


Vec = np.ndarray


@dataclass(frozen=True)
class Cue:
    element: str
    start: int
    end: int
    move: str

    def contains(self, frame: int) -> bool:
        return self.start <= frame <= self.end

    def phase(self, frame: int) -> float:
        return float(np.clip((frame - self.start) / max(1, self.end - self.start), 0.0, 1.0))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--trajectory", type=Path, required=True)
    p.add_argument("--cues", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--grid", type=int, default=64)
    p.add_argument("--seed", type=int, default=9137)
    p.add_argument("--padding", type=float, default=1.8)
    p.add_argument("--only", choices=["all", "fire", "air", "frost", "water", "earth", "lightning"], default="all")
    return p.parse_args()


def v3(value) -> Vec:
    a = np.asarray(value, dtype=np.float64)
    if a.shape != (3,) or not np.isfinite(a).all():
        raise ValueError(f"Expected finite vec3, got {value!r}")
    return a


def normalize(a: Vec, fallback=(0.0, 1.0, 0.0)) -> Vec:
    n = float(np.linalg.norm(a))
    return a / n if n > 1e-10 else v3(fallback)


def load_inputs(path: Path, cue_path: Path):
    data = json.loads(path.read_text())
    frames = data["frames"]
    if not frames:
        raise ValueError("Trajectory has no frames")
    cues_raw = json.loads(cue_path.read_text())
    cues = [Cue(str(c["element"]).lower(), int(c["start"]), int(c["end"]), str(c["move"])) for c in cues_raw["cues"]]
    return data, frames, cues


def world_bounds(frames, padding: float):
    points = []
    for f in frames:
        for key in ("root", "right_hand", "left_hand", "axe_head", "axe_tail"):
            points.append(v3(f[key]))
    p = np.vstack(points)
    lo, hi = p.min(0), p.max(0)
    lo -= padding
    hi += padding
    lo[1] = min(lo[1], -0.2)
    hi[1] = max(hi[1], 3.2)
    span = hi - lo
    span[span < 1.0] = 1.0
    return lo, lo + span


def write_cgrid(path: Path, density: np.ndarray) -> None:
    if density.ndim != 3:
        raise ValueError("density must be Z,Y,X")
    z, y, x = density.shape
    a = np.ascontiguousarray(np.maximum(density, 0), dtype="<f4")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        f.write(struct.pack("<3i", x, y, z))
        f.write(a.tobytes())


def world_to_grid(p: Vec, lo: Vec, hi: Vec, shape) -> Vec:
    xyz = (p - lo) / (hi - lo)
    # Return x,y,z voxel coordinates.
    return xyz * (np.asarray(shape[::-1], dtype=float) - 1)


def make_grid(shape, lo, hi):
    z, y, x = shape
    xs = np.linspace(lo[0], hi[0], x)
    ys = np.linspace(lo[1], hi[1], y)
    zs = np.linspace(lo[2], hi[2], z)
    zz, yy, xx = np.meshgrid(zs, ys, xs, indexing="ij")
    return xx, yy, zz


def trilinear(field: np.ndarray, gx, gy, gz) -> np.ndarray:
    zmax, ymax, xmax = np.array(field.shape) - 1
    gx = np.clip(gx, 0, xmax)
    gy = np.clip(gy, 0, ymax)
    gz = np.clip(gz, 0, zmax)
    x0 = np.floor(gx).astype(np.int32); x1 = np.minimum(x0 + 1, xmax)
    y0 = np.floor(gy).astype(np.int32); y1 = np.minimum(y0 + 1, ymax)
    z0 = np.floor(gz).astype(np.int32); z1 = np.minimum(z0 + 1, zmax)
    tx = gx - x0; ty = gy - y0; tz = gz - z0
    c00 = field[z0, y0, x0] * (1-tx) + field[z0, y0, x1] * tx
    c01 = field[z0, y1, x0] * (1-tx) + field[z0, y1, x1] * tx
    c10 = field[z1, y0, x0] * (1-tx) + field[z1, y0, x1] * tx
    c11 = field[z1, y1, x0] * (1-tx) + field[z1, y1, x1] * tx
    c0 = c00 * (1-ty) + c01 * ty
    c1 = c10 * (1-ty) + c11 * ty
    return c0 * (1-tz) + c1 * tz


def laplacian(a: np.ndarray) -> np.ndarray:
    return (
        np.roll(a, 1, 0) + np.roll(a, -1, 0) +
        np.roll(a, 1, 1) + np.roll(a, -1, 1) +
        np.roll(a, 1, 2) + np.roll(a, -1, 2) - 6*a
    )


def splat(field: np.ndarray, p: Vec, lo: Vec, hi: Vec, radius: float, amount: float) -> None:
    shape = field.shape
    g = world_to_grid(p, lo, hi, shape)
    voxel = (hi - lo) / (np.asarray(shape[::-1]) - 1)
    rv = np.maximum(1, np.ceil(radius / voxel).astype(int))
    x0 = max(0, int(g[0]-rv[0])); x1 = min(shape[2], int(g[0]+rv[0]+1))
    y0 = max(0, int(g[1]-rv[1])); y1 = min(shape[1], int(g[1]+rv[1]+1))
    z0 = max(0, int(g[2]-rv[2])); z1 = min(shape[0], int(g[2]+rv[2]+1))
    if x0 >= x1 or y0 >= y1 or z0 >= z1:
        return
    xs = np.arange(x0, x1); ys = np.arange(y0, y1); zs = np.arange(z0, z1)
    zz, yy, xx = np.meshgrid(zs, ys, xs, indexing="ij")
    d2 = ((xx-g[0])*voxel[0])**2 + ((yy-g[1])*voxel[1])**2 + ((zz-g[2])*voxel[2])**2
    field[z0:z1, y0:y1, x0:x1] += amount * np.exp(-d2 / max(1e-8, 2*radius*radius))


def splat_segment(field, a, b, lo, hi, radius, amount):
    length = float(np.linalg.norm(b-a))
    steps = max(2, int(math.ceil(length / max(radius*.45, 1e-3))))
    for t in np.linspace(0, 1, steps):
        splat(field, a*(1-t)+b*t, lo, hi, radius, amount/steps*3.0)


def evolve_smoke(density, temperature, dt, lo, hi, source, source_prev, strength, swirl=1.0):
    z, y, x = density.shape
    # Velocity is analytic but world-space and state-dependent: buoyancy +
    # two counter-rotating curls around the weapon axis.
    zz, yy, xx = np.meshgrid(np.arange(z), np.arange(y), np.arange(x), indexing="ij")
    wx = lo[0] + xx/(x-1)*(hi[0]-lo[0])
    wy = lo[1] + yy/(y-1)*(hi[1]-lo[1])
    wz = lo[2] + zz/(z-1)*(hi[2]-lo[2])
    c = source
    dx, dz = wx-c[0], wz-c[2]
    r2 = dx*dx + dz*dz + .12
    vx = -swirl * dz / r2 * np.exp(-r2/2.8)
    vz = swirl * dx / r2 * np.exp(-r2/2.8)
    vy = .42 + 1.45*np.clip(temperature, 0, 1.5)
    # Add weapon sweep momentum.
    weapon_v = (source-source_prev) / max(dt, 1e-6)
    local = np.exp(-((wx-c[0])**2 + (wy-c[1])**2 + (wz-c[2])**2)/1.2)
    vx += weapon_v[0] * .22 * local
    vy += weapon_v[1] * .10 * local
    vz += weapon_v[2] * .22 * local

    sx = (x-1)/(hi[0]-lo[0]); sy = (y-1)/(hi[1]-lo[1]); sz = (z-1)/(hi[2]-lo[2])
    gx = xx - vx*dt*sx
    gy = yy - vy*dt*sy
    gz = zz - vz*dt*sz
    density[:] = trilinear(density, gx, gy, gz)
    temperature[:] = trilinear(temperature, gx, gy, gz)
    density += .025 * laplacian(density)
    temperature += .020 * laplacian(temperature)
    density *= math.exp(-.62*dt)
    temperature *= math.exp(-1.05*dt)
    splat_segment(density, source_prev, source, lo, hi, .18, .85*strength)
    splat_segment(temperature, source_prev, source, lo, hi, .13, 1.25*strength)
    np.maximum(density, 0, out=density)
    np.maximum(temperature, 0, out=temperature)


def write_obj(path: Path, vertices: Iterable[Vec], faces: Iterable[tuple[int, int, int]]) -> None:
    verts = [v3(v) for v in vertices]
    faces = list(faces)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# CYBR ELEMENTS generated geometry\n")
        for v in verts:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for a,b,c in faces:
            f.write(f"f {a+1} {b+1} {c+1}\n")


def append_octahedron(vertices, faces, center, radius, stretch, rotation):
    base = np.array([
        [ 1,0,0],[-1,0,0],[0, 1,0],[0,-1,0],[0,0, 1],[0,0,-1]
    ], dtype=float)
    base *= np.array([radius, radius*stretch, radius])
    base = base @ rotation.T + center
    start = len(vertices); vertices.extend(base)
    local = [(0,2,4),(4,2,1),(1,2,5),(5,2,0),(4,3,0),(1,3,4),(5,3,1),(0,3,5)]
    faces.extend(tuple(start+i for i in tri) for tri in local)


def rotation_from_rng(rng):
    q = rng.normal(size=4); q /= np.linalg.norm(q)
    w,x,y,z = q
    return np.array([
        [1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w)],
        [2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w)],
        [2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)]
    ])


def frost_frame(frame, cue, anchor, tangent, seed, path):
    rng = np.random.default_rng(seed + cue.start)
    n = 34
    verts=[]; faces=[]
    phase=cue.phase(frame)
    for i in range(n):
        born=(i/n)*.72
        age=max(0.0, phase-born)
        if phase < born: continue
        side = normalize(np.cross(tangent, np.array([0,1,0.])), (1,0,0))
        direction = normalize(tangent*.35 + side*rng.uniform(-1,1) + np.array([0,rng.uniform(.1,.85),0]))
        speed=rng.uniform(1.2,3.8)
        c=anchor + direction*speed*age + np.array([0,-2.6*age*age,0])
        r=rng.uniform(.025,.10)*(1.0-.35*age)
        append_octahedron(verts,faces,c,r,rng.uniform(2.0,6.0),rotation_from_rng(rng))
    write_obj(path,verts,faces)


def water_frame(frame, cue, current, previous, seed, path):
    rng=np.random.default_rng(seed+frame)
    verts=[];faces=[]
    direction=normalize(current-previous,(1,0,0))
    side=normalize(np.cross(direction,[0,1,0]),(0,0,1))
    up=normalize(np.cross(side,direction),(0,1,0))
    phase=cue.phase(frame)
    # Ribbon follows the last weapon segment and curls upward.
    rings=18; sides=8
    for i in range(rings):
        t=i/(rings-1)
        center=previous*(1-t)+current*t
        center += up*(math.sin(t*math.pi)*(.22+.28*phase)) + side*math.sin(t*5.5+phase*8)*.06
        radius=.075*(.35+math.sin(t*math.pi)**.6)
        for j in range(sides):
            a=2*math.pi*j/sides
            verts.append(center + side*math.cos(a)*radius + up*math.sin(a)*radius)
    for i in range(rings-1):
        for j in range(sides):
            a=i*sides+j;b=i*sides+(j+1)%sides;c=(i+1)*sides+(j+1)%sides;d=(i+1)*sides+j
            faces.extend([(a,b,c),(a,c,d)])
    for _ in range(16):
        c=current+rng.normal(size=3)*np.array([.22,.18,.22])
        append_octahedron(verts,faces,c,rng.uniform(.012,.035),rng.uniform(.6,1.6),rotation_from_rng(rng))
    write_obj(path,verts,faces)


def earth_frame(frame, cue, impact, seed, path):
    rng=np.random.default_rng(seed+cue.start)
    age=(frame-cue.start)/30.0
    verts=[];faces=[]
    n=46
    for i in range(n):
        angle=2*math.pi*i/n+rng.uniform(-.08,.08)
        speed=rng.uniform(1.1,4.4)
        radial=np.array([math.cos(angle),0,math.sin(angle)])
        c=impact + radial*speed*age + np.array([0, rng.uniform(1.2,3.6)*age-4.9*age*age, 0])
        if c[1] < 0: c[1]=0
        r=rng.uniform(.035,.14)
        append_octahedron(verts,faces,c,r,rng.uniform(.45,1.3),rotation_from_rng(rng))
    write_obj(path,verts,faces)


def displaced_branch(a, b, depth, rng, spread, out):
    if depth <= 0:
        out.append([a.tolist(), b.tolist()])
        return
    mid=(a+b)*.5
    length=np.linalg.norm(b-a)
    jitter=rng.normal(size=3)
    jitter-=normalize(b-a)*np.dot(jitter,normalize(b-a))
    mid += normalize(jitter,(0,1,0))*spread*length*rng.uniform(.25,.65)
    displaced_branch(a,mid,depth-1,rng,spread*.78,out)
    displaced_branch(mid,b,depth-1,rng,spread*.78,out)
    if depth >= 2 and rng.random()<.7:
        branch_dir=normalize((mid-a)+rng.normal(size=3)*length,(0,1,0))
        tip=mid+branch_dir*length*rng.uniform(.25,.55)
        displaced_branch(mid,tip,depth-2,rng,spread*.72,out)


def lightning_frame(frame, cue, anchor, seed, path):
    rng=np.random.default_rng(seed+frame*7919)
    phase=cue.phase(frame)
    segments=[]
    targets=[]
    # Ground strikes + air branches, all anchored to the animated weapon.
    for i in range(5):
        a=2*math.pi*i/5+phase*2.2
        target=anchor+np.array([math.cos(a)*rng.uniform(1.3,3.2), -max(.1,anchor[1]), math.sin(a)*rng.uniform(1.3,3.2)])
        targets.append(target)
    for target in targets:
        displaced_branch(anchor,target,4,rng,.24,segments)
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps({"frame":frame,"segments":segments},indent=2))


def choose_cue(cues, element, frame):
    for c in cues:
        if c.element == element and c.contains(frame):
            return c
    return None


def main():
    a=parse_args()
    trajectory,frames,cues=load_inputs(a.trajectory,a.cues)
    out=a.out;out.mkdir(parents=True,exist_ok=True)
    lo,hi=world_bounds(frames,a.padding)
    n=max(24,int(a.grid));shape=(n,n,n)
    fps=float(trajectory.get("fps",30))
    dt=1.0/fps
    fire=np.zeros(shape,np.float32);heat=np.zeros_like(fire)
    air=np.zeros(shape,np.float32);air_heat=np.zeros_like(air)
    manifest={"version":1,"fps":fps,"bounds":{"lower":lo.tolist(),"upper":hi.tolist()},"frames":{}}
    previous=v3(frames[0]["axe_head"])
    previous_frame=int(frames[0]["frame"])
    frame_lookup={int(r["frame"]):r for r in frames}

    for row in frames:
        frame=int(row["frame"])
        dt=max(1.0/fps,(frame-previous_frame)/fps)
        head=v3(row["axe_head"]); tail=v3(row["axe_tail"])
        tangent=normalize(head-tail,(1,0,0))
        assets={}

        fire_cue=choose_cue(cues,"fire",frame)
        if a.only in ("all","fire") and fire_cue:
            strength=math.sin(math.pi*fire_cue.phase(frame))**.35
            evolve_smoke(fire,heat,dt,lo,hi,head,previous,strength,swirl=1.6)
            density_path=out/"fire"/f"density_{frame:04d}.cgrid"
            write_cgrid(density_path,fire)
            threshold=np.percentile(heat[heat>0],75) if np.any(heat>0) else 999
            hot=np.argwhere(heat>=threshold)
            core=[]
            if len(hot):
                for z,y,x in hot[::max(1,len(hot)//24)][:24]:
                    p=lo+(np.array([x/(n-1),y/(n-1),z/(n-1)])*(hi-lo))
                    core.append({"p":p.tolist(),"temperature":float(heat[z,y,x])})
            core_path=out/"fire"/f"core_{frame:04d}.json";core_path.parent.mkdir(parents=True,exist_ok=True)
            core_path.write_text(json.dumps({"frame":frame,"points":core},indent=2))
            assets["fire_density"]=str(density_path.relative_to(out));assets["fire_core"]=str(core_path.relative_to(out))
        else:
            fire*=math.exp(-2.2*dt);heat*=math.exp(-2.8*dt)

        lightning_cue=choose_cue(cues,"lightning",frame)
        if a.only in ("all","lightning") and lightning_cue:
            p=out/"lightning"/f"frame_{frame:04d}.json"
            lightning_frame(frame,lightning_cue,head,a.seed,p)
            assets["lightning"]=str(p.relative_to(out))

        air_cue=choose_cue(cues,"air",frame) or lightning_cue
        if a.only in ("all","air") and air_cue:
            strength=.45+1.2*math.sin(math.pi*air_cue.phase(frame))**2
            evolve_smoke(air,air_heat,dt,lo,hi,head,previous,strength,swirl=3.0)
            p=out/"air"/f"density_{frame:04d}.cgrid";write_cgrid(p,air*.42)
            assets["air_density"]=str(p.relative_to(out))
        else:
            air*=math.exp(-1.8*dt);air_heat*=math.exp(-2.0*dt)

        frost_cue=choose_cue(cues,"frost",frame)
        if a.only in ("all","frost") and frost_cue:
            p=out/"frost"/f"frame_{frame:04d}.obj"
            frost_frame(frame,frost_cue,head,tangent,a.seed,p)
            assets["frost_mesh"]=str(p.relative_to(out))

        water_cue=choose_cue(cues,"water",frame)
        if a.only in ("all","water") and water_cue:
            p=out/"water"/f"frame_{frame:04d}.obj"
            water_frame(frame,water_cue,head,previous,a.seed,p)
            assets["water_mesh"]=str(p.relative_to(out))

        earth_cue=choose_cue(cues,"earth",frame)
        if a.only in ("all","earth") and earth_cue:
            source_row=frame_lookup.get(earth_cue.start)
            if source_row is None:
                source_row=min(frames,key=lambda r:abs(int(r["frame"])-earth_cue.start))
            impact=v3(source_row["axe_head"])
            impact[1]=0
            p=out/"earth"/f"frame_{frame:04d}.obj"
            earth_frame(frame,earth_cue,impact,a.seed,p)
            assets["earth_mesh"]=str(p.relative_to(out))

        manifest["frames"][str(frame)]=assets
        previous=head
        previous_frame=frame

    (out/"manifest.json").write_text(json.dumps(manifest,indent=2))
    print(json.dumps({"frames":len(frames),"bounds":manifest["bounds"],"out":str(out.resolve())},indent=2))


if __name__=="__main__":
    main()
