const {chromium}=require('C:/Users/alexf/AppData/Local/npm-cache/_npx/31e32ef8478fbf80/node_modules/playwright');
const fs=require('fs'),path=require('path');
(async()=>{const variant=process.argv[2],production=process.argv[3]==='all',frames=production?Array.from({length:120},(_,i)=>i):process.argv[3].split(',').map(Number),out=path.join(__dirname,(production?'production-':'frames-')+variant);fs.mkdirSync(out,{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=d3d11','--enable-gpu'],executablePath:"C:/Users/alexf/AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe"}),page=await b.newPage({viewport:production?{width:1920,height:1080}:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`http://127.0.0.1:8767/elements/motion/water/?variant=${variant}&capture=1&frame=${frames[0]}`);await page.waitForFunction(()=>window.WATER?.ready||window.WATER_ERROR,{},{timeout:120000});const error=await page.evaluate(()=>window.WATER_ERROR);if(error)throw Error(error);
const journal=path.join(out,'recorded.json'),recorded=production&&fs.existsSync(journal)?JSON.parse(fs.readFileSync(journal)):[];
try{for(const f of frames){if(production&&recorded.includes(f))continue;if(production){const cache=path.resolve(__dirname,'../../outputs/cybrdelic-type/elements/motion/water/cache',variant);let m;while(true){try{m=JSON.parse(fs.readFileSync(path.join(cache,'manifest.json')));const stats=JSON.parse(fs.readFileSync(path.join(__dirname,'mesh-'+variant+'.json')));if(m.frames.length>f&&stats.some(x=>x.frame===f))break}catch{}await new Promise(r=>setTimeout(r,1000))}await page.evaluate(m=>Object.assign(WATER.manifest,m),m);}const info=await page.evaluate(f=>WATER.loadFrame(f),f);await page.screenshot({path:path.join(out,String(f).padStart(4,'0')+'.jpg'),type:'jpeg',quality:97});if(info.glError)throw Error('GL '+info.glError);if(production){recorded.push(f);fs.writeFileSync(journal,JSON.stringify(recorded));}if(f%8===0||!production)console.log('FRAME',variant,f);}
fs.writeFileSync(path.join(__dirname,(production?'production-capture-':'capture-')+variant+'.json'),JSON.stringify({frames,resolution:production?[1920,1080]:[1920,1080],errors,renderer:await page.evaluate(()=>WATER.renderer.info())}));if(errors.length)throw Error(errors.join('\n'));}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

