
(async()=>{const [tests,trail]=await Promise.all([fetch('shared-tests.json').then(r=>r.json()),fetch('shared-trail.json').then(r=>r.json())]);const xy=p=>[(p[0]+5.25)*1920/10.5,120+(4.2-p[1])*768/4.2];const path=trail.frames.filter(f=>f.t>=trail.start&&f.t<=trail.start+trail.write).map((f,i)=>(i?'L':'M')+xy(f.p).join(',')).join(' ');
for(const t of tests){const a=document.createElement('article');a.innerHTML=`<h2>${t.title}<a href="${t.video}" download>MP4</a></h2><div class="media"><video controls muted playsinline preload="auto" poster="${t.id}-shared-poster.jpg" data-video="${t.video}"></video><svg class="guide" viewBox="0 0 1920 1080"><path d="${path}" fill="none" stroke="#acc3cd" stroke-width="3" stroke-opacity=".55" stroke-dasharray="10 12"/><circle r="9" fill="#e4edf2"/></svg></div><p>${t.note}</p>`;document.querySelector('#tests').append(a)}
const videos=[...document.querySelectorAll('video')],play=document.querySelector('#play'),scrub=document.querySelector('#scrub');let playing=false,seeking=false;
function paint(t){document.querySelector('#time').textContent=t.toFixed(2)+' / 4s';scrub.value=t;const f=trail.frames[Math.min(trail.frames.length-1,Math.round((t+.025)*trail.sampleRate))],p=xy(f.p);document.querySelectorAll('.guide circle').forEach(c=>{c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);c.style.opacity=f.on>0?1:0})}
function pause(){playing=false;videos.forEach(v=>v.pause());play.textContent='Play all'}
async function seek(t){pause();seeking=true;await Promise.all(videos.map(v=>new Promise(resolve=>{if(Math.abs(v.currentTime-t)<.001)return resolve();const finish=()=>resolve();v.addEventListener('seeked',finish,{once:true});v.currentTime=Math.min(t,v.duration-.001)})));seeking=false;paint(t)}
async function start(){if(videos[0].currentTime>3.95)await seek(0);await seek(videos[0].currentTime);playing=true;await Promise.all(videos.map(v=>v.play()));play.textContent='Pause all'}
videos.forEach((v,i)=>{v.addEventListener('play',()=>{if(!playing){videos.forEach(o=>{if(o!==v)o.pause()});play.textContent='Play all'}});v.addEventListener('pointerdown',()=>{if(playing){playing=false;videos.forEach(o=>{if(o!==v)o.pause()});play.textContent='Play all'}});v.addEventListener('seeking',()=>{if(!playing&&!seeking){videos.forEach(o=>{if(o!==v)o.pause()})}})});
play.onclick=()=>playing?pause():start();document.querySelector('#restart').onclick=async()=>{await seek(0);await start()};scrub.oninput=()=>seek(+scrub.value);document.querySelector('#guide').onchange=e=>document.body.classList.toggle('show-guide',e.target.checked);
const assets=await Promise.all(tests.map(async t=>{const r=await fetch(t.video);if(!r.ok)throw Error('Could not load '+t.video);return r.blob()}));videos.forEach((v,i)=>{v.src=URL.createObjectURL(assets[i])});
await Promise.all(videos.map(v=>new Promise((resolve,reject)=>{if(v.readyState>=2)return resolve();v.addEventListener('loadeddata',resolve,{once:true});v.addEventListener('error',()=>reject(Error('Could not load '+v.src)),{once:true});}))); 
play.disabled=false;scrub.disabled=false;document.querySelector('#restart').disabled=false;document.querySelector('#status').textContent='4 seconds / 30 fps / synchronized playback';videos[0].onended=()=>{pause();paint(4)};
function tick(){document.querySelectorAll('.guide circle').forEach((c,i)=>{const f=trail.frames[Math.min(trail.frames.length-1,Math.round((videos[i].currentTime+.025)*trail.sampleRate))],p=xy(f.p);c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);c.style.opacity=f.on>0?1:0});if(playing&&!seeking){const t=videos[0].currentTime;for(const v of videos.slice(1))if(Math.abs(v.currentTime-t)>.06)v.currentTime=t;paint(t)}requestAnimationFrame(tick)}paint(0);requestAnimationFrame(tick);window.SHARED={ready:true,videos,seek,start,pause,trail};
})().catch(e=>{document.querySelector('#status').textContent=e.message;window.SHARED_ERROR=e.message});