from pathlib import Path
import cv2, hashlib, json, shutil, subprocess
import numpy as np
from PIL import Image

B=Path(__file__).resolve().parent
P=B.parents[2]/'outputs/cybrdelic-type/elements/motion/bending'
baseline=json.loads((B.parent/'bending-rebuild/validation.json').read_text())
unchanged={}
for name in ['earth','fire','air']:
    actual=hashlib.sha256((P/f'{name}.mp4').read_bytes()).hexdigest()
    assert actual==next(v['sha256'] for v in baseline['videos'] if v['element']==name)
    unchanged[name]=actual
m=json.loads((B/'water-particles/manifest.json').read_text());last=m['frames'][-1]
assert m['complete'] and len(m['frames'])==120
assert all(x['finite'] and x['pressure']['converged'] and x['sourceVolumeBalance']==0 and x['capacityRejected']==0 for x in m['frames'])
rows=[json.loads((B/'water-mesh-calibrated'/f'{f:04}.json').read_text()) for f in range(120)]
volume=max(abs(r.get('totalRepresentedVolumeError',0)) for r in rows)
sprayVolume=max(abs(r.get('sprayVolumeRelativeError',0)) for r in rows)
assert volume<.025 and sprayVolume<1e-5
videos=[]
for name,poster in [('water',42),('lightning',37)]:
    path=B/f'{name}-v3.mp4'
    probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-select_streams','v:0','-show_entries','stream=codec_name,width,height,pix_fmt,r_frame_rate,duration,nb_frames','-of','json',str(path)]))['streams'][0]
    assert (probe['width'],probe['height'],probe['nb_frames'],probe['r_frame_rate'])==(1920,1080,'120','30/1')
    cap=cv2.VideoCapture(str(path));frames=0;cornerBackground=[];means=[];crossings=[]
    while True:
        ok,a=cap.read()
        if not ok:break
        if frames==poster:Image.fromarray(cv2.cvtColor(a,cv2.COLOR_BGR2RGB)).save(B/f'{name}-v3.jpg',quality=94)
        corners=[float(np.quantile(p,.95)) for p in [a[:24,:24],a[:24,-24:],a[-24:,:24],a[-24:,-24:]]]
        cornerBackground.append(float(np.median(corners)));means.append(round(float(a.mean()),5))
        if max(corners)>3:crossings.append(frames)
        frames+=1
    cap.release();assert frames==120 and max(cornerBackground)<=3
    videos.append({'element':name,'file':path.name,'metadata':probe,'decodedFrames':frames,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'bytes':path.stat().st_size,'backgroundCornerMaximum':max(cornerBackground),'cornerCrossingFrames':crossings,'frameMeanRGB':means})
water={'frames':120,'particles':last['particles'],'pressureSolves':last['pressureSolves'],'pressureFailures':last['pressureFailures'],'maxSurfaceVolumeError':volume,'maxSprayVolumeError':sprayVolume,'maxSprayFragments':max(r.get('sprayFragments',0) for r in rows)}
report={'passed':True,'videos':videos,'water':water,'unchanged':unchanged}
(B/'validation.json').write_text(json.dumps(report,indent=2))

prov=json.loads((P/'provenance.json').read_text());prov['revision']='water-lightning-rebuild-3'
prov['elements']['water']={
 'file':'water-v3.mp4','previous':'water-v2.mp4','dynamics':'Fresh 281 x 188 x 48 APIC/FLIP simulation, h 0.015, lower transverse source strain, pressure and capillary solve',
 'particles':last['particles'],'render':'Cycles OptiX 96 samples at 2560 x 1440; downsampled to 1080p; 0.65-frame motion-blur shutter',
 'spray':'Connected marker clusters remain coherent drops. Isolated single markers become persistent, volume-normalized 24-fragment parcels with a lognormal size distribution, inherited momentum, a bounded capillary-scale dispersion closure, gravity and quadratic air drag.',
 'surface':'Persistent sparse/bulk classification; broader reconstruction support with an expanded isovalue root bracket, non-shrinking Taubin smoothing and a volume-error gate',
 'limitations':['Spray breakup is a subgrid graphics closure; it is not directly resolved atomization.','Global surface volume matching does not prove local incompressibility.','The bending trajectory and near-nozzle steering force remain authored.'],
 'validation':water}
prov['elements']['lightning']={
 'file':'lightning-v3.mp4','previous':'lightning-v2.mp4',
 'dynamics':'World-space 2D dielectric-breakdown growth with successive electrode targets in a heterogeneous conductivity corridor; no curved-strip deformation',
 'atmosphere':'200 x 112 x 40 transported aerosol, 3D velocity advection, buoyancy and FFT pressure projection; approximate single scattering from the channel',
 'render':'2x supersampled core and corona; separate leader and return-stroke exposures; transported low-density haze on black',
 'limitations':['The guide electrodes and conductivity corridor are authored.','The electrical model is not full 3D plasma electrodynamics.','Aerosol is an authored medium, not smoke generated by lightning in clean air.','Channel illumination uses an approximate nearest-channel single-scattering model.'],
 'reference':'https://gamma-web.iacs.umd.edu/LIGHTNING/lightning.pdf'}
prov['limitations']=['These are guided visual-effects simulations.','Water spray finer than the FLIP grid is modeled through a mass-accounted parcel approximation.','Lightning uses a guided 2D electrical growth model with a 3D aerosol, rather than a full plasma simulation.']
prov['rebuildValidation']={'water':water,'videos':[{k:v for k,v in r.items() if k!='frameMeanRGB'} for r in videos],'unchangedAcceptedClips':unchanged}
for name in ['water','lightning']:
    for ext in ['mp4','jpg']:shutil.copy2(B/f'{name}-v3.{ext}',P/f'{name}-v3.{ext}')
(P/'provenance.json').write_text(json.dumps(prov,indent=2));shutil.copy2(B/'index.html',P/'index.html')
print(json.dumps({'published':True,'water':water,'videos':[{k:v for k,v in r.items() if k in ['element','metadata','bytes','decodedFrames','backgroundCornerMaximum']} for r in videos]},indent=2))
