/** Scene-graph inspector/editor backed by typed dependency validation. */
(function(){'use strict';const $=id=>document.getElementById(id);let graph,selected='physics';
const overlay=document.createElement('section');overlay.style.cssText='display:none;position:fixed;z-index:20;inset:4%;background:#101923f5;border:1px solid #557580;border-radius:12px;padding:20px;overflow:auto;color:#e6f0f4;font:13px Arial';
overlay.innerHTML='<div style="display:flex;justify-content:space-between"><h2>Typed scene graph / SI units</h2><button id="graphClose">Close</button></div><svg id="graphCanvas" viewBox="0 0 880 320" style="width:100%;max-height:320px"></svg><div style="display:flex;gap:20px"><div style="flex:1"><h3 id="graphTitle"></h3><textarea id="graphParameters" spellcheck="false" style="width:100%;height:210px;background:#071017;color:#cbe6e4;padding:12px;border:1px solid #47606a;font:12px monospace"></textarea><div style="margin-top:10px"><button id="graphApply">Apply node</button> <button id="graphSave">Save graph</button> <button id="graphLoad">Load graph</button><input type="file" id="graphFile" accept=".json" hidden></div></div><div style="flex:1"><h3>Cache invalidation and memory</h3><pre id="graphStatus" style="white-space:pre-wrap;line-height:1.6"></pre><p>Surface edits rebuild through tools/run_graph.mjs and tools/mesh_iii.py; cached geometry is never silently relabeled as a new simulation.</p></div></div>';
document.body.appendChild(overlay);const ns='http://www.w3.org/2000/svg';
function fileDownload(data,name){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([data]));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function message(s){$('graphStatus').textContent=s;}
function draw(){const svg=$('graphCanvas');svg.replaceChildren();const positions={source:[10,130],physics:[185,130],surface:[360,130],material:[360,10],camera:[535,10],lighting:[710,10],render:[620,130],export:[620,250]};
 for(const node of graph.document.nodes)for(const input of node.inputs??[]){const [x,y]=positions[input]??[10,10],[a,b]=positions[node.id]??[10,10],p=document.createElementNS(ns,'path');p.setAttribute('d',`M ${x+150} ${y+25} C ${x+190} ${y+25}, ${a-40} ${b+25}, ${a} ${b+25}`);p.setAttribute('fill','none');p.setAttribute('stroke','#456875');p.setAttribute('stroke-width','2');svg.appendChild(p);}
 for(const node of graph.document.nodes){const [x,y]=positions[node.id]??[10,10],g=document.createElementNS(ns,'g'),r=document.createElementNS(ns,'rect'),t=document.createElementNS(ns,'text');r.setAttribute('x',x);r.setAttribute('y',y);r.setAttribute('width',150);r.setAttribute('height',50);r.setAttribute('rx',6);r.setAttribute('fill',node.id===selected?'#28535b':'#1c2d3a');r.setAttribute('stroke','#6a929b');t.setAttribute('x',x+12);t.setAttribute('y',y+30);t.setAttribute('fill','#e4f3f1');t.textContent=node.id.toUpperCase();g.append(r,t);g.style.cursor='pointer';g.onclick=()=>{selected=node.id;draw();};svg.appendChild(g);}
 const n=graph.byId.get(selected);$('graphTitle').textContent=n.id+' / '+n.type;$('graphParameters').value=JSON.stringify(n.parameters,null,2);
}
$('openGraph').onclick=()=>{try{if(!CYBR.ready)throw Error('Wait for the simulator to initialize.');if(!graph||graph.compile().config.nameKey!==CYBR.config.nameKey)graph=CYBR_PIPELINE.createSceneGraph(CYBR.config);draw();overlay.style.display='block';const memory=CYBR_PIPELINE.planMemory(graph.compile().config);message(`Estimated working envelope: ${(memory.totalEstimatedBytes/2**20).toFixed(0)} MiB\nPlanning estimate, not measured adapter memory.\n\nSelect a node to inspect parameters and dependencies.`);}catch(e){alert(e.message);}};
$('graphClose').onclick=()=>overlay.style.display='none';
$('graphApply').onclick=async()=>{try{const result=graph.patch(selected,JSON.parse($('graphParameters').value)),compiled=graph.compile(),r=CYBR.renderer;
 if(selected==='material'){r.material.uniforms.uIOR.value=compiled.material.ior;r.material.uniforms.uAbsorption.value.set(...compiled.material.absorption);r.draw();}
 if(selected==='lighting'){r.renderer.toneMappingExposure=compiled.lighting.exposure;r.draw();}if(selected==='camera')CYBR.setShot(compiled.camera.shot);
 if(selected==='physics'){const s=CYBR.settings(),p=graph.byId.get('physics').parameters;s.flip=p.flip??s.flip;s.parameters={...s.parameters,...p};await CYBR.restoreSettings(s);}
 message('Invalidated:\n'+result.invalidated.join(' → ')+'\n\nSurface/source edits are applied by the headless graph runner.\nPhysics edits restart the browser solver; lighting/material/camera edits do not.');draw();}catch(e){message(e.stack??e.message);}};
$('graphSave').onclick=()=>fileDownload(JSON.stringify(graph.toJSON(),null,2),'CYBR_FLIP_III_scene_graph.json');$('graphLoad').onclick=()=>$('graphFile').click();$('graphFile').onchange=async e=>{try{graph=new CYBR_PIPELINE.SceneGraph(JSON.parse(await e.target.files[0].text()));selected='physics';draw();message('Graph loaded and validated. Apply nodes or run the saved graph headlessly.');}catch(error){message(error.message);}};
$('saveCheckpoint').onclick=async()=>{try{CYBR.setPaused(true);const b=await CYBR.saveCheckpoint();fileDownload(b,'CYBR_FLIP_III_checkpoint.cfc3');}catch(e){alert(e.message);}};
$('loadCheckpoint').onclick=()=>$('checkpointFile').click();$('checkpointFile').onchange=async e=>{try{CYBR.setPaused(true);await CYBR.loadCheckpoint(await e.target.files[0].arrayBuffer());}catch(error){alert(error.message);}};
window.CYBR_GRAPH_UI={get graph(){return graph;},open:()=>$('openGraph').click()};
})();
