#!/usr/bin/env node
/**
 * High-density field visualization of the leading shrinking-core mechanism in
 * the OpenAI Navier–Stokes blowup construction.
 *
 * IMPORTANT: this is not a liquid surface and it is not the exact theorem
 * field.  It is an explicit smooth axisymmetric divergence-free similarity
 * surrogate whose leading time exponents match the construction:
 *
 *   L_r ~ tau^(1/2)
 *   L_z ~ tau^(1/2-h)
 *   |u_theta|, |u_z| ~ tau^(-1/2-h)
 *   |u_r| ~ tau^(-1/2)
 *   E_core ~ tau^(1/2-3h)
 *
 * Geometry:
 *   - dense instantaneous stream tubes
 *   - directional arrowheads embedded in the tubes
 *   - a shrinking similarity-core wire cage
 *   - eight absolute-speed material bins referenced to frame 0
 *
 * The complete E/U/Pi pieces, annular-pulse correction and forcing from the
 * proof are intentionally not claimed here.
 */
import fs from 'node:fs';
import path from 'node:path';

const argv = process.argv.slice(2);
const arg = (name, fallback) => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : fallback;
};

const outDir = path.resolve(arg('--out', 'rendered/navier-stokes-field'));
const frames = Math.max(3, Number(arg('--frames', '24')));
const tauMax = Number(arg('--tau-max', '0.28'));
const tauMin = Number(arg('--tau-min', '0.004'));
const h = Number(arg('--h', '0.009'));
const tubeSides = Math.max(5, Number(arg('--tube-sides', '7')));
const seedRings = Math.max(8, Number(arg('--seed-rings', '18')));
const steps = Math.max(16, Number(arg('--steps', '30')));

fs.mkdirSync(outDir, { recursive: true });

const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const len=a=>Math.sqrt(dot(a,a));
const norm=a=>{ const n=len(a); return n>1e-14?mul(a,1/n):[0,0,0]; };

function scales(tau) {
  const A=0.5+h, D=0.5-h;
  return {
    tau,A,D,
    radial:tau**0.5,
    axial:tau**D,
    tangential:tau**(-A),
    radialVelocity:tau**(-0.5),
    energyScale:tau**(0.5-3*h),
  };
}

/**
 * Smooth axisymmetric divergence-free field.
 *
 * The poloidal part comes from
 *   psi = C/tau r^2 z exp[-0.5((r/Lr)^2 + 0.72(z/Lz)^2)]
 * and the swirl is theta-independent.  Coefficients only shape the similarity
 * profile; the time exponents above are unchanged.
 */
function velocity(p,tau) {
  const s=scales(tau);
  const [x,y,z]=p;
  const r=Math.hypot(x,y);
  const R=r/s.radial;
  const Z=z/s.axial;
  const env=Math.exp(-0.5*(R*R+0.72*Z*Z));
  const C=0.62;
  const swirl=2.15;

  // A smooth divergence-free poloidal field generated by the streamfunction.
  const ur=-(C/tau)*r*(1-0.72*Z*Z)*env;
  const uz=(C/tau)*z*(2-R*R)*env;
  const utheta=swirl*s.tangential*R*env*(1+0.08*Math.tanh(Z));

  const c=r>1e-14?x/r:1;
  const sn=r>1e-14?y/r:0;
  return [ur*c-utheta*sn, ur*sn+utheta*c, uz];
}

function normalizedRadius(p,s) {
  return Math.hypot(Math.hypot(p[0],p[1])/s.radial,p[2]/s.axial);
}

function integrate(seed,tau,sign) {
  const s=scales(tau);
  const ds=0.070*s.radial;
  const out=[seed.slice()];
  let p=seed.slice();
  for (let i=0;i<steps;i++) {
    // Midpoint integration on the normalized direction field gives cleaner
    // stream geometry than forward Euler without changing the field itself.
    const v0=velocity(p,tau);
    const d0=norm(v0);
    if (len(d0)<1e-12) break;
    const pm=add(p,mul(d0,sign*0.5*ds));
    const dm=norm(velocity(pm,tau));
    if (len(dm)<1e-12) break;
    const q=add(p,mul(dm,sign*ds));
    if (!q.every(Number.isFinite) || normalizedRadius(q,s)>3.35) break;
    out.push(q);
    p=q;
  }
  return out;
}

function streamline(seed,tau) {
  const a=integrate(seed,tau,-1).reverse();
  const b=integrate(seed,tau,+1);
  return a.slice(0,-1).concat(b);
}

function mesh(){ return {v:[],f:[]}; }

function addCylinder(m,a,b,r,sides=tubeSides) {
  const axis=sub(b,a), L=len(axis);
  if (!(L>1e-10)) return;
  const w=mul(axis,1/L);
  const ref=Math.abs(w[2])<0.88?[0,0,1]:[0,1,0];
  const u=norm(cross(w,ref));
  const v=cross(w,u);
  const base=m.v.length;
  for (const p of [a,b]) {
    for (let j=0;j<sides;j++) {
      const t=2*Math.PI*j/sides;
      m.v.push(add(p,add(mul(u,r*Math.cos(t)),mul(v,r*Math.sin(t)))));
    }
  }
  for (let j=0;j<sides;j++) {
    const k=(j+1)%sides;
    const a0=base+j,a1=base+k,b0=base+sides+j,b1=base+sides+k;
    m.f.push([a0,a1,b1],[a0,b1,b0]);
  }
}

function addCone(m,baseCenter,tip,r,sides=7) {
  const axis=sub(tip,baseCenter),L=len(axis);
  if (!(L>1e-10)) return;
  const w=mul(axis,1/L);
  const ref=Math.abs(w[2])<0.88?[0,0,1]:[0,1,0];
  const u=norm(cross(w,ref));
  const v=cross(w,u);
  const base=m.v.length;
  for (let j=0;j<sides;j++) {
    const t=2*Math.PI*j/sides;
    m.v.push(add(baseCenter,add(mul(u,r*Math.cos(t)),mul(v,r*Math.sin(t)))));
  }
  const ti=m.v.length;
  m.v.push(tip.slice());
  for (let j=0;j<sides;j++) {
    const k=(j+1)%sides;
    m.f.push([base+j,base+k,ti]);
  }
}

const speedCuts=[0.18,0.35,0.70,1.40,2.80,5.60,11.20];
function speedBin(q) {
  for (let i=0;i<speedCuts.length;i++) if (q<speedCuts[i]) return i;
  return speedCuts.length;
}

function addFieldGeometry(lines,tau,bins,tubeRadius,referenceSpeed) {
  const s=scales(tau);
  let maxSpeed=0,segments=0,arrows=0;
  for (const pts of lines) {
    for (let i=0;i+1<pts.length;i++) {
      const a=pts[i],b=pts[i+1];
      const mid=mul(add(a,b),0.5);
      const speed=len(velocity(mid,tau));
      maxSpeed=Math.max(maxSpeed,speed);
      const bi=speedBin(speed/referenceSpeed);
      addCylinder(bins[bi],a,b,tubeRadius,tubeSides);
      segments++;

      // Direction glyphs are sparse enough to keep the field readable.
      if (i>0 && i%11===0) {
        const dir=norm(velocity(mid,tau));
        const base=add(mid,mul(dir,-0.025*s.radial));
        const tip=add(mid,mul(dir, 0.085*s.radial));
        addCone(bins[bi],base,tip,0.032*s.radial,7);
        arrows++;
      }
    }
  }
  return {maxSpeed,segments,arrows};
}

function addCoreCage(m,s) {
  const tube=0.0075*s.radial;
  const loop=pts=>{
    for(let i=0;i<pts.length;i++) addCylinder(m,pts[i],pts[(i+1)%pts.length],tube,6);
  };

  // Latitudes.
  for (const zeta of [-0.90,-0.55,0,0.55,0.90]) {
    const z=1.35*zeta*s.axial;
    const rr=1.35*s.radial*Math.sqrt(Math.max(0,1-zeta*zeta));
    const pts=[];
    for(let i=0;i<64;i++){
      const t=2*Math.PI*i/64;
      pts.push([rr*Math.cos(t),rr*Math.sin(t),z]);
    }
    loop(pts);
  }

  // Meridians.
  for(let a=0;a<12;a++){
    const theta=2*Math.PI*a/12;
    const pts=[];
    for(let i=0;i<72;i++){
      const t=2*Math.PI*i/72;
      const rr=1.35*s.radial*Math.cos(t);
      const z=1.35*s.axial*Math.sin(t);
      pts.push([rr*Math.cos(theta),rr*Math.sin(theta),z]);
    }
    loop(pts);
  }
}

function writeObj(file,m) {
  let s='# CYBR ELEMENTS Navier-Stokes field visualization mesh\n';
  for (const p of m.v) s+=`v ${p[0].toPrecision(10)} ${p[1].toPrecision(10)} ${p[2].toPrecision(10)}\n`;
  for (const f of m.f) s+=`f ${f[0]+1} ${f[1]+1} ${f[2]+1}\n`;
  fs.writeFileSync(file,s);
}

function numericEnergyAndMax(tau) {
  const s=scales(tau);
  const nr=48,nz=96;
  const rMax=4*s.radial,zMax=4*s.axial;
  const dr=rMax/nr,dz=2*zMax/nz;
  let E=0,maxU=0;
  for(let ir=0;ir<nr;ir++){
    const r=(ir+0.5)*dr;
    for(let iz=0;iz<nz;iz++){
      const z=-zMax+(iz+0.5)*dz;
      const u=velocity([r,0,z],tau);
      const q=dot(u,u);
      const dV=2*Math.PI*r*dr*dz;
      E+=0.5*q*dV;
      maxU=Math.max(maxU,Math.sqrt(q));
    }
  }
  return {energy:E,maxSpeed:maxU};
}

const taus=Array.from({length:frames},(_,i)=>{
  const a=i/(frames-1);
  return tauMax*Math.pow(tauMin/tauMax,a);
});

const first=numericEnergyAndMax(taus[0]);
const referenceSpeed=first.maxSpeed;
const rows=[];

for(let fi=0;fi<frames;fi++){
  const tau=taus[fi],s=scales(tau);
  const lines=[];
  const zetas=[-1.30,-0.90,-0.55,-0.25,0,0.25,0.55,0.90,1.30];
  const layers=[0.48,0.82,1.12];

  for (const layer of layers) {
    for (const zeta of zetas) {
      for(let a=0;a<seedRings;a++){
        const theta=2*Math.PI*(a/seedRings+0.043*zeta+0.017*layer);
        const rr=layer*s.radial*(1+0.045*Math.sin(3*theta+0.7*zeta));
        lines.push(streamline([rr*Math.cos(theta),rr*Math.sin(theta),zeta*s.axial],tau));
      }
    }
  }

  const bins=Array.from({length:8},()=>mesh());
  const fieldStats=addFieldGeometry(lines,tau,bins,0.0155*s.radial,referenceSpeed);
  const cage=mesh();
  addCoreCage(cage,s);

  const frameDir=path.join(outDir,'frames',String(fi).padStart(4,'0'));
  fs.mkdirSync(frameDir,{recursive:true});
  const binFiles=[];
  for(let b=0;b<bins.length;b++){
    const p=path.join(frameDir,`speed_${b}.obj`);
    writeObj(p,bins[b]);
    binFiles.push(path.relative(outDir,p));
  }
  const cagePath=path.join(frameDir,'core_cage.obj');
  writeObj(cagePath,cage);

  const numeric=numericEnergyAndMax(tau);
  const row={
    frame:fi,tau,t:1-tau,
    radialScale:s.radial,
    axialScale:s.axial,
    aspectRatio:s.axial/s.radial,
    characteristicSpeed:s.tangential,
    characteristicRadialSpeed:s.radialVelocity,
    expectedEnergyScale:s.energyScale,
    numericEnergy:numeric.energy,
    numericEnergyRelative:numeric.energy/first.energy,
    gridMaxSpeed:numeric.maxSpeed,
    maxSpeedRelative:numeric.maxSpeed/referenceSpeed,
    streamlineMaxSpeed:fieldStats.maxSpeed,
    streamlineSegments:fieldStats.segments,
    arrowheads:fieldStats.arrows,
    speedBins:binFiles,
    speedCuts,
    cage:path.relative(outDir,cagePath),
    disclosure:'Leading-core divergence-free visualization surrogate; not the full E/U/Pi + annular-pulse + forcing construction.'
  };
  rows.push(row);
  console.log(JSON.stringify(row));
}

const config={
  frames,tauMax,tauMin,h,tubeSides,seedRings,steps,
  field:'smooth axisymmetric divergence-free streamfunction + swirl',
  exponents:{
    radialScale:'tau^(1/2)',
    axialScale:'tau^(1/2-h)',
    dominantVelocity:'tau^(-1/2-h)',
    energy:'tau^(1/2-3h)'
  },
  speedCuts,
  referenceSpeed,
  noImageGeneration:true,
  disclosure:'High-density visualization of the leading shrinking-core mechanism. It is not the exact full theorem field and omits the complete E/U/Pi construction, annular-pulse correction and forcing.'
};

fs.writeFileSync(path.join(outDir,'config.json'),JSON.stringify(config,null,2));
fs.writeFileSync(path.join(outDir,'metrics.json'),JSON.stringify(rows,null,2));
