import fs from 'node:fs';
import path from 'node:path';

/**
 * Field-line visualization of the leading similarity scaling described in
 * OpenAI's 2026 finite-time Navier-Stokes blowup result.
 *
 * This is not a numerical reproduction of the full proof. It visualizes a
 * smooth axisymmetric divergence-free surrogate with the same leading length
 * and velocity exponents. Unlike the older tracer-isosurface preview, this
 * output has no implied liquid/free surface: the OBJ meshes are tubes following
 * instantaneous velocity streamlines.
 */

function parseArgs(argv) {
  const out = {
    out: 'rendered/navier-stokes-field',
    frames: 10,
    tauMax: 0.28,
    tauMin: 0.004,
    h: 0.009,
    seedAngles: 12,
    steps: 22,
  };
  for (let i = 2; i < argv.length; i++) {
    const k = argv[i], v = argv[i + 1];
    if (k === '--out') { out.out = v; i++; }
    else if (k === '--frames') { out.frames = Number(v); i++; }
    else if (k === '--tau-max') { out.tauMax = Number(v); i++; }
    else if (k === '--tau-min') { out.tauMin = Number(v); i++; }
    else if (k === '--h') { out.h = Number(v); i++; }
    else if (k === '--seed-angles') { out.seedAngles = Number(v); i++; }
    else if (k === '--steps') { out.steps = Number(v); i++; }
    else if (k === '--help') {
      console.log('node generate_field.mjs --out DIR [--frames N] [--tau-max X] [--tau-min X] [--h X]');
      process.exit(0);
    } else throw new Error('Unknown argument: ' + k);
  }
  if (!(out.frames >= 3 && out.tauMax > out.tauMin && out.tauMin > 0)) {
    throw new Error('Require frames >=3 and tauMax > tauMin > 0');
  }
  if (!(out.h > 0 && out.h < 0.01)) throw new Error('Require 0 < h < 0.01');
  return out;
}

function tauSequence(count, maxTau, minTau) {
  const a = Math.log(maxTau), b = Math.log(minTau);
  return Array.from({ length: count }, (_, i) => Math.exp(a + (b - a) * i / (count - 1)));
}

function scales(tau, h) {
  const A = 0.5 + h, D = 0.5 - h;
  return {
    A, D,
    radial: tau ** 0.5,
    axial: tau ** D,
    tangentialVelocity: tau ** (-A),
    radialVelocity: tau ** (-0.5),
    expectedEnergyScale: tau ** (0.5 - 3 * h),
  };
}

// Axisymmetric divergence-free surrogate. Poloidal component is generated by
// psi = alpha r^2 z exp(-(R^2+Z^2)/2); the swirl is theta-independent.
function velocity(x, y, z, tau, h) {
  const s = scales(tau, h);
  const r = Math.hypot(x, y);
  const theta = Math.atan2(y, x);
  const R = r / s.radial;
  const Z = z / s.axial;
  const g = Math.exp(-0.5 * (R * R + Z * Z));
  const alpha = 0.56 / tau;

  const ur = -alpha * r * (1 - Z * Z) * g;
  const uz = alpha * z * (2 - R * R) * g;

  const swirlEnvelope = Math.exp(-0.5 * (R * R + 0.72 * Z * Z));
  const utheta = 1.12 * s.tangentialVelocity * R * swirlEnvelope * (1 + 0.055 * Math.tanh(Z));

  const c = Math.cos(theta), sn = Math.sin(theta);
  return [
    ur * c - utheta * sn,
    ur * sn + utheta * c,
    uz,
  ];
}

function norm(v) { return Math.hypot(v[0], v[1], v[2]); }
function cross(a, b) {
  return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]];
}
function normalize(v) {
  const n = Math.max(1e-12, norm(v));
  return [v[0]/n, v[1]/n, v[2]/n];
}
function add(a,b) { return [a[0]+b[0], a[1]+b[1], a[2]+b[2]]; }
function mul(a,s) { return [a[0]*s,a[1]*s,a[2]*s]; }

function integrateDirection(seed, tau, h, direction, steps) {
  const s = scales(tau, h);
  const ds = 0.095 * s.radial;
  const out = [seed];
  let p = seed;
  for (let i = 0; i < steps; i++) {
    const v0 = velocity(p[0], p[1], p[2], tau, h);
    const m0 = norm(v0);
    if (m0 < 1e-10) break;
    const d0 = mul(v0, direction / m0);
    const mid = add(p, mul(d0, 0.5 * ds));
    const vm = velocity(mid[0], mid[1], mid[2], tau, h);
    const mm = norm(vm);
    if (mm < 1e-10) break;
    const dm = mul(vm, direction / mm);
    p = add(p, mul(dm, ds));
    const R = Math.hypot(p[0], p[1]) / s.radial;
    const Z = Math.abs(p[2]) / s.axial;
    if (R > 3.6 || Z > 4.4) break;
    out.push(p);
  }
  return out;
}

function makeStreamline(seed, tau, h, steps) {
  const back = integrateDirection(seed, tau, h, -1, steps).reverse();
  const fwd = integrateDirection(seed, tau, h, +1, steps);
  return back.slice(0, -1).concat(fwd);
}

function emptyMesh() { return { v: [], f: [] }; }

function addTubeSegment(mesh, a, b, radius, sides = 6) {
  const tangent = normalize([b[0]-a[0], b[1]-a[1], b[2]-a[2]]);
  let ref = Math.abs(tangent[2]) < 0.85 ? [0,0,1] : [0,1,0];
  const n1 = normalize(cross(tangent, ref));
  const n2 = normalize(cross(tangent, n1));
  const base = mesh.v.length;

  for (const p of [a,b]) {
    for (let j = 0; j < sides; j++) {
      const ang = 2*Math.PI*j/sides;
      const off = add(mul(n1, Math.cos(ang)*radius), mul(n2, Math.sin(ang)*radius));
      mesh.v.push(add(p, off));
    }
  }
  for (let j = 0; j < sides; j++) {
    const j1 = (j+1)%sides;
    const a0 = base+j, a1 = base+j1, b0 = base+sides+j, b1 = base+sides+j1;
    mesh.f.push([a0,b0,b1], [a0,b1,a1]);
  }
}

function writeObj(file, mesh, comment) {
  const lines = ['# ' + comment];
  for (const p of mesh.v) lines.push(`v ${p[0].toPrecision(9)} ${p[1].toPrecision(9)} ${p[2].toPrecision(9)}`);
  for (const f of mesh.f) lines.push(`f ${f[0]+1} ${f[1]+1} ${f[2]+1}`);
  fs.writeFileSync(file, lines.join('\n') + '\n');
}

function buildFieldMeshes(tau, h, seedAngles, steps) {
  const s = scales(tau, h);
  const meshes = { slow: emptyMesh(), mid: emptyMesh(), fast: emptyMesh() };
  const radii = [0.42, 0.72, 1.02, 1.34];
  const zs = [-2.5, -1.4, -0.55, 0.0, 0.55, 1.4, 2.5];
  const characteristic = s.tangentialVelocity;
  let maxSpeed = 0;
  let segmentCount = 0;

  for (const R0 of radii) {
    for (const Z0 of zs) {
      for (let k = 0; k < seedAngles; k++) {
        const theta = 2*Math.PI*(k + 0.37*(R0 + Z0 + 4))/seedAngles;
        const seed = [
          s.radial * R0 * Math.cos(theta),
          s.radial * R0 * Math.sin(theta),
          s.axial * Z0,
        ];
        const line = makeStreamline(seed, tau, h, steps);
        for (let i = 0; i + 1 < line.length; i++) {
          const a = line[i], b = line[i+1];
          const mid = [(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2];
          const speed = norm(velocity(mid[0],mid[1],mid[2],tau,h));
          maxSpeed = Math.max(maxSpeed, speed);
          const q = speed / Math.max(1e-9, characteristic);
          const band = q < 0.28 ? 'slow' : (q < 0.68 ? 'mid' : 'fast');
          const radius = s.radial * (band === 'fast' ? 0.010 : band === 'mid' ? 0.008 : 0.0065);
          addTubeSegment(meshes[band], a, b, radius, 6);
          segmentCount++;
        }
      }
    }
  }
  return { meshes, maxSpeed, segmentCount };
}

// Cylindrical quadrature of 1/2 |u|^2 over a similarity box. This is the
// surrogate field energy, not the theorem's exact solution energy.
function energyIntegral(tau, h) {
  const s = scales(tau, h);
  const nR = 72, nZ = 96;
  const Rmax = 4.0, Zmax = 4.5;
  const dR = Rmax / nR, dZ = 2*Zmax / nZ;
  let E = 0;
  for (let i = 0; i < nR; i++) {
    const R = (i + 0.5)*dR;
    const r = R*s.radial;
    for (let j = 0; j < nZ; j++) {
      const Z = -Zmax + (j + 0.5)*dZ;
      const z = Z*s.axial;
      const v = velocity(r, 0, z, tau, h);
      const speed2 = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
      const dV = 2*Math.PI * r * (s.radial*dR) * (s.axial*dZ);
      E += 0.5*speed2*dV;
    }
  }
  return E;
}

function main() {
  const args = parseArgs(process.argv);
  const out = path.resolve(args.out);
  const fieldDir = path.join(out, 'field');
  fs.mkdirSync(fieldDir, {recursive:true});

  const taus = tauSequence(args.frames, args.tauMax, args.tauMin);
  const metrics = [];
  const config = {
    source: 'OpenAI 2026 Navier-Stokes blowup leading similarity scaling',
    disclosure: 'Instantaneous streamline tubes of a smooth divergence-free surrogate matching the leading core exponents. No liquid/free surface is implied. This is not the exact E/U/Pi/forcing construction from the proof.',
    h: args.h,
    tauMax: args.tauMax,
    tauMin: args.tauMin,
    frames: args.frames,
    visualization: 'velocity streamlines, fixed-world + similarity-tracking cameras',
    noImageGeneration: true,
  };
  fs.writeFileSync(path.join(out,'config.json'), JSON.stringify(config,null,2));

  const E0 = energyIntegral(taus[0], args.h);
  for (let frame = 0; frame < taus.length; frame++) {
    const tau = taus[frame];
    const s = scales(tau,args.h);
    const built = buildFieldMeshes(tau,args.h,args.seedAngles,args.steps);
    const files = {};
    for (const band of ['slow','mid','fast']) {
      const file = path.join(fieldDir, `${String(frame).padStart(4,'0')}_${band}.obj`);
      writeObj(file,built.meshes[band], `velocity streamline band=${band}; tau=${tau}`);
      files[band] = path.relative(out,file).replaceAll('\\','/');
    }
    const energy = energyIntegral(tau,args.h);
    const row = {
      frame,
      tau,
      t: 1-tau,
      radialScale: s.radial,
      axialScale: s.axial,
      aspectRatio: s.axial/s.radial,
      characteristicTangentialVelocity: s.tangentialVelocity,
      characteristicRadialVelocity: s.radialVelocity,
      expectedEnergyScale: s.expectedEnergyScale,
      surrogateEnergy: energy,
      normalizedSurrogateEnergy: energy/E0,
      sampledMaxSpeed: built.maxSpeed,
      streamlineSegments: built.segmentCount,
      field: files,
    };
    metrics.push(row);
    console.log(JSON.stringify(row));
  }

  fs.writeFileSync(path.join(out,'metrics.json'), JSON.stringify(metrics,null,2));
  fs.writeFileSync(path.join(out,'manifest.json'), JSON.stringify({
    complete:true,
    config:'config.json',
    metrics:'metrics.json',
    field:'field/',
    noImageGeneration:true,
  },null,2));
}

main();
